# my global config
global:
  scrape_interval: 15s 
  evaluation_interval: 15s 
  external_labels:
    monitor: "codelab-monitor"

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: docker

    static_configs:
      - targets: ["host.docker.internal:9323"]